# Generated by Django 6.0.1 on 2026-02-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('category', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('VIDEO', 'Video'), ('DOC', 'Documentation'), ('COURSE', 'Course')], max_length=20)),
                ('trait_alignment', models.CharField(max_length=1)),
            ],
        ),
    ]
