# Generated by Django 6.0.1 on 2026-02-03 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_careerpath_milestone_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='assessments.milestone'),
        ),
    ]
