# Generated by Django 6.0.1 on 2026-02-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerpath',
            name='trait_type',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
