# Generated by Django 6.0.1 on 2026-02-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_careerpath_trait_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='mentor_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('PENDING_REVIEW', 'Pending Review'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='submission_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='submission_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
