# Generated by Django 6.0.1 on 2026-02-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_achievement_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userachievement',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
