# Generated by Django 6.0.1 on 2026-03-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_userachievement_is_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='badge_icon',
            field=models.CharField(help_text='Lucide icon identifier.', max_length=50),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='scores',
            field=models.JSONField(help_text="Dictionary of RIASEC scores: {'R': 10, ...}"),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='top_trait',
            field=models.CharField(help_text="Primary trait or blended code (e.g., 'IR').", max_length=50),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='trait_type',
            field=models.CharField(help_text="The code (e.g., 'I') that triggers this path.", max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='trait_alignment',
            field=models.CharField(help_text='RIASEC code this resource aligns with.', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, help_text='Sequence order for the quiz.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(help_text='The assessment question text.', max_length=500),
        ),
    ]
