# Generated by Django 6.0.1 on 2026-02-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_company_customuser_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expertise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
