# Generated by Django 6.0.1 on 2026-02-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_level_customuser_xp_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_seen_onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
