# Generated by Django 6.0.1 on 2026-02-07 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_has_seen_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'MENTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
