# Generated by Django 6.0.1 on 2026-02-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customuser_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_celebrated_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
