# Generated by Django 6.0.1 on 2026-02-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_has_celebrated_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
